  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install kubectl and minikube
      run: |
        sudo apt-get update
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=docker
        minikube update-context

    - name: Configure kubectl
      run: |
        mkdir -p ~/.kube
        minikube kubectl -- config view --flatten > ~/.kube/config
        kubectl cluster-info

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/redis.yaml --validate=false
        kubectl apply -f k8s/backend.yaml --validate=false
        kubectl apply -f k8s/frontend.yaml --validate=false
        
        kubectl set image deployment/backend backend=${{ env.BACKEND_IMAGE }}:${{ github.sha }}
        kubectl set image deployment/frontend frontend=${{ env.FRONTEND_IMAGE }}:${{ github.sha }}