name: Deploy Messenger to Kubernetes

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  setup-infra:
    runs-on: ubuntu-latest
    steps:
    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=docker --force
        minikube kubectl -- version --client

    - name: Prepare kubeconfig
      run: |
        mkdir -p ~/.kube
        minikube kubectl -- config view --flatten > ~/.kube/config
        kubectl cluster-info

  deploy:
    needs: setup-infra
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure kubectl
      run: |
        mkdir -p ~/.kube
        minikube kubectl -- config view --flatten > ~/.kube/config
        kubectl get nodes

    - name: Deploy Redis
      run: kubectl apply -f k8s/redis.yaml

    - name: Deploy Application
      run: |
        kubectl apply -f k8s/backend.yaml
        kubectl apply -f k8s/frontend.yaml
        kubectl get pods -w
