name: Deploy Messenger
on: [push]
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd backend
          docker build -t yourusername/messenger-backend:latest .
          docker push yourusername/messenger-backend:latest
  deploy:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: kubectl apply -f k8s/
