name: Deploy Messenger to Kubernetes

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE: ghcr.io/lentra0/messenger-docker-k8s-backend
  FRONTEND_IMAGE: ghcr.io/lentra0/messenger-docker-k8s-frontend

jobs:
  setup-infra:
    runs-on: ubuntu-latest
    steps:
    - name: Install Minikube and kubectl
      run: |
        # Установка Minikube
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

        # Установка kubectl
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install kubectl /usr/local/bin/kubectl

        # Запуск кластера
        minikube start --driver=docker
        minikube addons enable ingress

    - name: Prepare kubeconfig
      id: kubeconfig
      run: |
        mkdir -p ~/.kube
        minikube kubectl -- config view --flatten > ~/.kube/config
        echo "KUBE_CONFIG=$(cat ~/.kube/config | base64 -w0)" >> $GITHUB_OUTPUT

    outputs:
      kubeconfig: ${{ steps.kubeconfig.outputs.KUBE_CONFIG }}

  build-and-push:
    needs: setup-infra
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Backend
      run: |
        docker build -t ${{ env.BACKEND_IMAGE }}:${{ github.sha }} ./backend
        docker tag ${{ env.BACKEND_IMAGE }}:${{ github.sha }} ${{ env.BACKEND_IMAGE }}:latest
        docker push ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
        docker push ${{ env.BACKEND_IMAGE }}:latest

    - name: Build and push Frontend
      run: |
        docker build -t ${{ env.FRONTEND_IMAGE }}:${{ github.sha }} ./frontend
        docker tag ${{ env.FRONTEND_IMAGE }}:${{ github.sha }} ${{ env.FRONTEND_IMAGE }}:latest
        docker push ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
        docker push ${{ env.FRONTEND_IMAGE }}:latest

  deploy:
    needs: [setup-infra, build-and-push]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure kubectl
      run: |
        mkdir -p ~/.kube
        echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
        kubectl cluster-info
      env:
        KUBE_CONFIG: ${{ needs.setup-infra.outputs.kubeconfig }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/redis.yaml
        kubectl apply -f k8s/backend.yaml
        kubectl apply -f k8s/frontend.yaml

        kubectl set image deployment/backend backend=${{ env.BACKEND_IMAGE }}:${{ github.sha }}
        kubectl set image deployment/frontend frontend=${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

    - name: Verify deployment
      run: |
        echo "=== Pods ==="
        kubectl get pods -o wide
        echo "=== Services ==="
        kubectl get svc
        echo "=== Frontend URL ==="
        minikube service frontend-service --url
