name: Deploy Messenger to Kubernetes
run: |
    mkdir -p ~/.kube
    echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config

    kubectl cluster-info

    kubectl apply -f k8s/redis.yaml --validate=false
    kubectl apply -f k8s/backend.yaml --validate=false
    kubectl apply -f k8s/frontend.yaml --validate=false

    kubectl set image deployment/backend backend=$BACKEND_IMAGE:$GITHUB_SHA
    kubectl set image deployment/frontend frontend=$FRONTEND_IMAGE:$GITHUB_SHA
env:
    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE: ghcr.io/lentra0/messenger-docker-k8s-backend
  FRONTEND_IMAGE: ghcr.io/lentra0/messenger-docker-k8s-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Необходимо для push в GHCR

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  # Встроенный токен (не требует ручного создания)

    - name: Build and push Backend
      run: |
        docker build -t ${{ env.BACKEND_IMAGE }}:${{ github.sha }} ./backend
        docker tag ${{ env.BACKEND_IMAGE }}:${{ github.sha }} ${{ env.BACKEND_IMAGE }}:latest
        docker push ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
        docker push ${{ env.BACKEND_IMAGE }}:latest

    - name: Build and push Frontend
      run: |
        docker build -t ${{ env.FRONTEND_IMAGE }}:${{ github.sha }} ./frontend
        docker tag ${{ env.FRONTEND_IMAGE }}:${{ github.sha }} ${{ env.FRONTEND_IMAGE }}:latest
        docker push ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
        docker push ${{ env.FRONTEND_IMAGE }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/redis.yaml
        kubectl apply -f k8s/backend.yaml
        kubectl apply -f k8s/frontend.yaml

        kubectl set image deployment/backend backend=${{ env.BACKEND_IMAGE }}:${{ github.sha }}
        kubectl set image deployment/frontend frontend=${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}  # Закодированный kubeconfig (cat ~/.kube/config | base64 -w0)
